apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:latest
          ports:
            - containerPort: 3100
          volumeMounts:
            - mountPath: /data
              name: loki-storage
      volumes:
        - name: loki-storage
          persistentVolumeClaim:
            claimName: loki-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
---
# Define a 'Service' To Expose mysql to Other Services
apiVersion: v1
kind: Service
metadata:
  name: loki  # DNS name
  labels:
    app: loki
spec:
  ports:
    - port: 3100
      targetPort: 3100
  selector:       # mysql Pod Should contain same labels
    app: loki
  clusterIP: None