---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tempo-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/tempo-storage # Change this to your preferred path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:latest
          ports:
            - containerPort: 3100
            - containerPort: 9411
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo
            - name: tempo-data
              mountPath: /var/tempo/traces
          args:
            - --config.file=/etc/tempo/tempo.yaml
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /metrics
              port: 3100
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: tempo-data
          persistentVolumeClaim:
            claimName: tempo-pvc
        - name: tempo-config
          configMap:
            name: tempo-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
data:
  tempo.yaml: |
    server:
      http_listen_port: 3100

    distributor:
      receivers:
        zipkin:

    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/blocks
        wal:
          path: /var/tempo/wal

    metrics_generator:
      registry:
        external_labels:
          source: tempo
          cluster: minikube
      storage:
        path: /var/tempo/generator/wal
        remote_write:
          - url: http://prometheus-operated:9090/api/v1/write
          - url: http://event-collector:7777/write
            send_exemplars: true
      traces_storage:
        path: /var/tempo/generator/traces
    overrides:
      defaults:
        metrics_generator:
          processors: [service-graphs, span-metrics, local-blocks] # enables metrics generator
          generate_native_histograms: both
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  ports:
    - name: http
      port: 3200
      targetPort: 3100
    - name: zipkin
      port: 9411
      targetPort: 9411
  selector:
    app: tempo
  type: ClusterIP

